import os
gettext = lambda s: s
DATA_DIR = os.path.dirname(os.path.dirname(__file__))
"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.1.14.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = 'm-ccwefb9(moe3d4$1$wft-6=ym%2zvyp&5tp)657)0pw0+wb*'
DEBUG = True
ALLOWED_HOSTS = []
ROOT_URLCONF = 'mysite.urls'
WSGI_APPLICATION = 'mysite.wsgi.application'

AUTH_PASSWORD_VALIDATORS = [
     {'NAME':'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
     {'NAME':'django.contrib.auth.password_validation.MinimumLengthValidator'}, 
     {'NAME':'django.contrib.auth.password_validation.CommonPasswordValidator'}, 
     {'NAME':'django.contrib.auth.password_validation.NumericPasswordValidator'}
]

LANGUAGE_CODE = 'en'
TIME_ZONE = 'Asia/Tehran'
USE_I18N = True
USE_L10N = True
USE_TZ = True

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(DATA_DIR, 'media')
STATIC_ROOT = os.path.join(DATA_DIR, 'static')
STATICFILES_DIRS = os.path.join(BASE_DIR, 'mysite', 'static'),
SITE_ID = 1

TEMPLATES = [
    {'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [os.path.join(BASE_DIR, 'mysite', 'templates')], 
    #'APP_DIRS': True,
    'OPTIONS': {
        'context_processors': [
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
            'django.template.context_processors.i18n',
            'django.template.context_processors.debug',
            'django.template.context_processors.request',
            'django.template.context_processors.media',
            'django.template.context_processors.csrf',
            'django.template.context_processors.tz',
            'sekizai.context_processors.sekizai',
            'django.template.context_processors.static',
            'cms.context_processors.cms_settings'
        ], 
    'loaders': [
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader']
        }}
]

MIDDLEWARE = [
    'cms.middleware.utils.ApphookReloadMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware'
]
    
INSTALLED_APPS = [
    'djangocms_admin_style', 
    'django.contrib.auth',
    'django.contrib.contenttypes', 
    'django.contrib.sessions',
    'django.contrib.admin', 
    'django.contrib.sites',
    'django.contrib.sitemaps', 
    'django.contrib.staticfiles',
    'django.contrib.messages', 
    'cms', 
    'menus', 
    'sekizai', 
    'treebeard',
    'djangocms_text_ckeditor', 
    'filer', 
    'easy_thumbnails',
    'djangocms_bootstrap4',
    'djangocms_bootstrap4.contrib.bootstrap4_alerts',
    'djangocms_bootstrap4.contrib.bootstrap4_badge',
    'djangocms_bootstrap4.contrib.bootstrap4_card',
    'djangocms_bootstrap4.contrib.bootstrap4_carousel',
    'djangocms_bootstrap4.contrib.bootstrap4_collapse',
    'djangocms_bootstrap4.contrib.bootstrap4_content',
    'djangocms_bootstrap4.contrib.bootstrap4_grid',
    'djangocms_bootstrap4.contrib.bootstrap4_jumbotron',
    'djangocms_bootstrap4.contrib.bootstrap4_link',
    'djangocms_bootstrap4.contrib.bootstrap4_listgroup',
    'djangocms_bootstrap4.contrib.bootstrap4_media',
    'djangocms_bootstrap4.contrib.bootstrap4_picture',
    'djangocms_bootstrap4.contrib.bootstrap4_tabs',
    'djangocms_bootstrap4.contrib.bootstrap4_utilities', 
    'djangocms_file',
    'djangocms_icon', 
    'djangocms_link', 
    'djangocms_picture',
    'djangocms_style', 
    'djangocms_googlemap', 
    'djangocms_video', 
    'mysite',
    'aldryn_apphooks_config', 
    'aldryn_search',
    'parler', 
    'taggit', 
    'taggit_autosuggest',
    'meta', 
    'djangocms_blog', 
    'sortedm2m',
]

LANGUAGES = ('en', gettext('en')),
CMS_LANGUAGES = {
                (1): [{     'code': 'en', 
                            'name': gettext('en'),
                            'redirect_on_fallback': True, 
                            'public': True, 
                            'hide_untranslated': False
                      }],
                    'default': {
                        'redirect_on_fallback': True, 
                        'public': True,
                        'hide_untranslated': False}
                    }
CMS_TEMPLATES = [
                ('fullwidth.html', 'Fullwidth'), 
                ('sidebar_left.html','Sidebar Left'), 
                ('sidebar_right.html', 'Sidebar Right'), 
                ('home.html','Home Page'), 
                ('about.html', 'About Us'), 
                ('contact.html','Contact with Us'), 
                ('portfolio.html', 'Portfolio Page'), 
                ('blog.html','Blog Page'), 
                ('services.html', 'Services Page'), 
                ('team.html','Teams Page'), 
                ('pricing.html', 'Pricing Page')
]

X_FRAME_OPTIONS = 'SAMEORIGIN'
CMS_PERMISSION = True
CMS_PLACEHOLDER_CONF = {}
DATABASES = {'default':{
                        'CONN_MAX_AGE': 0, 
                        'ENGINE':'django.db.backends.sqlite3', 
                        'HOST': 'localhost', 
                        'NAME': 'project.db',
                        'PASSWORD': '',
                        'PORT': '',
                        'USER': ''
                        }
            }
            
THUMBNAIL_PROCESSORS = ('easy_thumbnails.processors.colorspace',
                        'easy_thumbnails.processors.autocrop',
                        'filer.thumbnail_processors.scale_and_crop_with_subject_location',
                        'easy_thumbnails.processors.filters')

META_SITE_PROTOCOL = 'https'
META_USE_SITES = True
META_USE_OG_PROPERTIES = True
META_USE_TWITTER_PROPERTIES = True
#META_USE_GOOGLEPLUS_PROPERTIES =True # django-meta 1.x+
#META_USE_SCHEMAORG_PROPERTIES =True  # django-meta 2.x+
META_USE_SCHEMAORG_PROPERTIES = True

HAYSTACK_CONNECTIONS = {
    'en': {
        'ENGINE': 'haystack.backends.solr_backend.SolrEngine',
        'URL': 'http://my-solr-server/solr/my-site-en/',
        'TIMEOUT': 60 * 5,
        'INCLUDE_SPELLING': True,
        'BATCH_SIZE': 100,
    },
}
HAYSTACK_ROUTERS = ['aldryn_search.router.LanguageRouter',]